# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10

    environment:
      MIX_ENV=test
      
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run: mix do compile --warnings-as-errors, coveralls.json
      - run:
          name: Running Inch CI documentation tests
          command: |
            MIX_ENV=docs mix deps.get
            MIX_ENV=docs mix inch.report
      - run:
          name: Upload Code Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
